<?php

namespace Proxies\__CG__\Trax\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TblMapmodule extends \Trax\AdminBundle\Entity\TblMapmodule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'mapid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'trainerid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'categoryid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'subcategory', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'moduleid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'description', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'scheduledate', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'customerid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'adminid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'createdat'];
        }

        return ['__isInitialized__', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'mapid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'trainerid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'categoryid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'subcategory', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'moduleid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'description', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'scheduledate', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'customerid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'adminid', '' . "\0" . 'Trax\\AdminBundle\\Entity\\TblMapmodule' . "\0" . 'createdat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TblMapmodule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMapid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMapid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMapid', []);

        return parent::getMapid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainerid($trainerid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainerid', [$trainerid]);

        return parent::setTrainerid($trainerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainerid', []);

        return parent::getTrainerid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryid($categoryid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryid', [$categoryid]);

        return parent::setCategoryid($categoryid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryid', []);

        return parent::getCategoryid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategory($subcategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategory', [$subcategory]);

        return parent::setSubcategory($subcategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategory', []);

        return parent::getSubcategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleid($moduleid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleid', [$moduleid]);

        return parent::setModuleid($moduleid);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleid', []);

        return parent::getModuleid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduledate($scheduledate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduledate', [$scheduledate]);

        return parent::setScheduledate($scheduledate);
    }

    /**
     * {@inheritDoc}
     */
    public function getScheduledate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheduledate', []);

        return parent::getScheduledate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerid($customerid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerid', [$customerid]);

        return parent::setCustomerid($customerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerid', []);

        return parent::getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminid($adminid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminid', [$adminid]);

        return parent::setAdminid($adminid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminid', []);

        return parent::getAdminid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedat($createdat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedat', [$createdat]);

        return parent::setCreatedat($createdat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedat', []);

        return parent::getCreatedat();
    }

}
